### ISSUE TITLE
Should source_status task fail when there are untracked changes?

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/ipa-project-template#19]
Currently, I get a warning when there are untracked changes, thanks to the `source_status` task, but the dependent tasks continue.

@tibuch did you intend that `source_status` blocks on untracked changes, or was it meant merely as a warning?

**Comment by imagejan** [comment]
Ah, ok, I must have initialized the repo before https://github.com/fmi-faim/ipa-project-template/commit/a2d1ee33c36e32764858bc9679e1e6a25d530564. Didn't see that commit before. So `log_commit` failed, instead of `build_config`. That makes sense.

Why aren't we _depending_ on `log_commit` then, instead of `pixi run log_commit`?

**Comment by tibuch** [comment]
Exactly. If you find a nicer solution, please let me know :)
