### ISSUE TITLE
Use INIT_CWD for pixi tasks in the current directory

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/ipa-project-template#25]
Pixi version `0.28.0` added the `INIT_CWD` environment variable to allow tasks to be run in the directory where they were invoked, instead of the project directory (parent of `pixi.toml`).

https://github.com/prefix-dev/pixi/pull/1798

We might want to reconsider our current setup with `WD=runs/example pixi run <...>` and instead use `INIT_CWD`. This means however that we'll have to go back to running the tasks from the `runs/<run_name>` subdirectory.

**Comment by tibuch** [comment]
I like that we run everything from the root directory at the moment. If we change it back it would also require the user to create the directory.

**Comment by imagejan** [comment]
With the current approach using `PIXI_PROJECT_ROOT` in the task definition, we don't need `INIT_CWD` anywhere. Closing this.
