### ISSUE TITLE
Add git as dependency

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/ipa-project-template#29]
Add `git` as default dependency. Otherwise `source_status` and `log_commit` tasks might not work out of the box. Or we find another way to ensure that `git` is available on the host system.

@imagejan any objection to adding `git` as default dependency from `conda-forge`?

**Comment by imagejan** [comment]
I am undecided. `git` as a dependency would certainly help achieve full reproducibility. But on systems that have `git` globally installed by default, it seems unnecessary to have our own copy of `git` in the project environment.

I raised a similar issue on the `pixi` repository a while ago, and while this package manager is a different scope than our project template, some of the same arguments pro and contra direct `git` dependency apply here:

https://github.com/prefix-dev/pixi/issues/1388

**Comment by tibuch** [comment]
Let's keep git outside for now. We use git to check the source status, but I think it is fine to assume (respectively teach users to install git) that git is available. 

After the copier copy process finished, the user will be informed that they should initialize the git repository.
