### ISSUE TITLE
Init git-repo

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/ipa-project-template#30]
Once the project template is copied we need to initialize the git-repo by running 
* `pixi run git init`
* `pixi run git add .`
* `pixi run git commit -m 'Initial commit.'`

We can either prompt these commands to the user in the output of the copier command or we can create a copier-task which takes care of this. 

I vote for the copier-task implementation.

**Comment by imagejan** [comment]
One concern: if the system didn't have a global git installation before cloning this template, chances are high that `git config [--global] user.name` and `git config [--global] user.email` are not correct (i.e., using some auto-generated pseudo mail address, for example).

**Comment by tibuch** [comment]
Added a `_message_after_copy` informing the user on how to init the git repo.
